/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.raidenmap.producerKey;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ProducerKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5653367945508380923L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProducerKey\",\"namespace\":\"io.raidenmap.producerKey\",\"fields\":[{\"name\":\"txHash\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProducerKey> ENCODER =
      new BinaryMessageEncoder<ProducerKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProducerKey> DECODER =
      new BinaryMessageDecoder<ProducerKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ProducerKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ProducerKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ProducerKey>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ProducerKey to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ProducerKey from a ByteBuffer. */
  public static ProducerKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence txHash;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProducerKey() {}

  /**
   * All-args constructor.
   * @param txHash The new value for txHash
   */
  public ProducerKey(java.lang.CharSequence txHash) {
    this.txHash = txHash;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txHash;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txHash = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'txHash' field.
   * @return The value of the 'txHash' field.
   */
  public java.lang.CharSequence getTxHash() {
    return txHash;
  }

  /**
   * Sets the value of the 'txHash' field.
   * @param value the value to set.
   */
  public void setTxHash(java.lang.CharSequence value) {
    this.txHash = value;
  }

  /**
   * Creates a new ProducerKey RecordBuilder.
   * @return A new ProducerKey RecordBuilder
   */
  public static io.raidenmap.producerKey.ProducerKey.Builder newBuilder() {
    return new io.raidenmap.producerKey.ProducerKey.Builder();
  }

  /**
   * Creates a new ProducerKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProducerKey RecordBuilder
   */
  public static io.raidenmap.producerKey.ProducerKey.Builder newBuilder(io.raidenmap.producerKey.ProducerKey.Builder other) {
    return new io.raidenmap.producerKey.ProducerKey.Builder(other);
  }

  /**
   * Creates a new ProducerKey RecordBuilder by copying an existing ProducerKey instance.
   * @param other The existing instance to copy.
   * @return A new ProducerKey RecordBuilder
   */
  public static io.raidenmap.producerKey.ProducerKey.Builder newBuilder(io.raidenmap.producerKey.ProducerKey other) {
    return new io.raidenmap.producerKey.ProducerKey.Builder(other);
  }

  /**
   * RecordBuilder for ProducerKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProducerKey>
    implements org.apache.avro.data.RecordBuilder<ProducerKey> {

    private java.lang.CharSequence txHash;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.raidenmap.producerKey.ProducerKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.txHash)) {
        this.txHash = data().deepCopy(fields()[0].schema(), other.txHash);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ProducerKey instance
     * @param other The existing instance to copy.
     */
    private Builder(io.raidenmap.producerKey.ProducerKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.txHash)) {
        this.txHash = data().deepCopy(fields()[0].schema(), other.txHash);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'txHash' field.
      * @return The value.
      */
    public java.lang.CharSequence getTxHash() {
      return txHash;
    }

    /**
      * Sets the value of the 'txHash' field.
      * @param value The value of 'txHash'.
      * @return This builder.
      */
    public io.raidenmap.producerKey.ProducerKey.Builder setTxHash(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.txHash = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'txHash' field has been set.
      * @return True if the 'txHash' field has been set, false otherwise.
      */
    public boolean hasTxHash() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'txHash' field.
      * @return This builder.
      */
    public io.raidenmap.producerKey.ProducerKey.Builder clearTxHash() {
      txHash = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProducerKey build() {
      try {
        ProducerKey record = new ProducerKey();
        record.txHash = fieldSetFlags()[0] ? this.txHash : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProducerKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProducerKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProducerKey>
    READER$ = (org.apache.avro.io.DatumReader<ProducerKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
