/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.raidenmap.event.channel;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ChannelOpened extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5758234313469786723L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ChannelOpened\",\"namespace\":\"io.raidenmap.event.channel\",\"fields\":[{\"name\":\"channelEvent\",\"type\":{\"type\":\"record\",\"name\":\"ChannelEvent\",\"fields\":[{\"name\":\"metadata\",\"type\":{\"type\":\"record\",\"name\":\"Metadata\",\"namespace\":\"io.raidenmap.event\",\"fields\":[{\"name\":\"blockNumber\",\"type\":\"long\"},{\"name\":\"blockTimestamp\",\"type\":\"long\"},{\"name\":\"eventTimestamp\",\"type\":\"long\"}]}},{\"name\":\"tokenNetworkAddress\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"}]}},{\"name\":\"participant1\",\"type\":\"string\"},{\"name\":\"participant2\",\"type\":\"string\"},{\"name\":\"settleTimeout\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ChannelOpened> ENCODER =
      new BinaryMessageEncoder<ChannelOpened>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ChannelOpened> DECODER =
      new BinaryMessageDecoder<ChannelOpened>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ChannelOpened> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ChannelOpened> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ChannelOpened>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ChannelOpened to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ChannelOpened from a ByteBuffer. */
  public static ChannelOpened fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public io.raidenmap.event.channel.ChannelEvent channelEvent;
  @Deprecated public java.lang.CharSequence participant1;
  @Deprecated public java.lang.CharSequence participant2;
  @Deprecated public long settleTimeout;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ChannelOpened() {}

  /**
   * All-args constructor.
   * @param channelEvent The new value for channelEvent
   * @param participant1 The new value for participant1
   * @param participant2 The new value for participant2
   * @param settleTimeout The new value for settleTimeout
   */
  public ChannelOpened(io.raidenmap.event.channel.ChannelEvent channelEvent, java.lang.CharSequence participant1, java.lang.CharSequence participant2, java.lang.Long settleTimeout) {
    this.channelEvent = channelEvent;
    this.participant1 = participant1;
    this.participant2 = participant2;
    this.settleTimeout = settleTimeout;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return channelEvent;
    case 1: return participant1;
    case 2: return participant2;
    case 3: return settleTimeout;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: channelEvent = (io.raidenmap.event.channel.ChannelEvent)value$; break;
    case 1: participant1 = (java.lang.CharSequence)value$; break;
    case 2: participant2 = (java.lang.CharSequence)value$; break;
    case 3: settleTimeout = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'channelEvent' field.
   * @return The value of the 'channelEvent' field.
   */
  public io.raidenmap.event.channel.ChannelEvent getChannelEvent() {
    return channelEvent;
  }

  /**
   * Sets the value of the 'channelEvent' field.
   * @param value the value to set.
   */
  public void setChannelEvent(io.raidenmap.event.channel.ChannelEvent value) {
    this.channelEvent = value;
  }

  /**
   * Gets the value of the 'participant1' field.
   * @return The value of the 'participant1' field.
   */
  public java.lang.CharSequence getParticipant1() {
    return participant1;
  }

  /**
   * Sets the value of the 'participant1' field.
   * @param value the value to set.
   */
  public void setParticipant1(java.lang.CharSequence value) {
    this.participant1 = value;
  }

  /**
   * Gets the value of the 'participant2' field.
   * @return The value of the 'participant2' field.
   */
  public java.lang.CharSequence getParticipant2() {
    return participant2;
  }

  /**
   * Sets the value of the 'participant2' field.
   * @param value the value to set.
   */
  public void setParticipant2(java.lang.CharSequence value) {
    this.participant2 = value;
  }

  /**
   * Gets the value of the 'settleTimeout' field.
   * @return The value of the 'settleTimeout' field.
   */
  public java.lang.Long getSettleTimeout() {
    return settleTimeout;
  }

  /**
   * Sets the value of the 'settleTimeout' field.
   * @param value the value to set.
   */
  public void setSettleTimeout(java.lang.Long value) {
    this.settleTimeout = value;
  }

  /**
   * Creates a new ChannelOpened RecordBuilder.
   * @return A new ChannelOpened RecordBuilder
   */
  public static io.raidenmap.event.channel.ChannelOpened.Builder newBuilder() {
    return new io.raidenmap.event.channel.ChannelOpened.Builder();
  }

  /**
   * Creates a new ChannelOpened RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ChannelOpened RecordBuilder
   */
  public static io.raidenmap.event.channel.ChannelOpened.Builder newBuilder(io.raidenmap.event.channel.ChannelOpened.Builder other) {
    return new io.raidenmap.event.channel.ChannelOpened.Builder(other);
  }

  /**
   * Creates a new ChannelOpened RecordBuilder by copying an existing ChannelOpened instance.
   * @param other The existing instance to copy.
   * @return A new ChannelOpened RecordBuilder
   */
  public static io.raidenmap.event.channel.ChannelOpened.Builder newBuilder(io.raidenmap.event.channel.ChannelOpened other) {
    return new io.raidenmap.event.channel.ChannelOpened.Builder(other);
  }

  /**
   * RecordBuilder for ChannelOpened instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ChannelOpened>
    implements org.apache.avro.data.RecordBuilder<ChannelOpened> {

    private io.raidenmap.event.channel.ChannelEvent channelEvent;
    private io.raidenmap.event.channel.ChannelEvent.Builder channelEventBuilder;
    private java.lang.CharSequence participant1;
    private java.lang.CharSequence participant2;
    private long settleTimeout;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.raidenmap.event.channel.ChannelOpened.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.channelEvent)) {
        this.channelEvent = data().deepCopy(fields()[0].schema(), other.channelEvent);
        fieldSetFlags()[0] = true;
      }
      if (other.hasChannelEventBuilder()) {
        this.channelEventBuilder = io.raidenmap.event.channel.ChannelEvent.newBuilder(other.getChannelEventBuilder());
      }
      if (isValidValue(fields()[1], other.participant1)) {
        this.participant1 = data().deepCopy(fields()[1].schema(), other.participant1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.participant2)) {
        this.participant2 = data().deepCopy(fields()[2].schema(), other.participant2);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.settleTimeout)) {
        this.settleTimeout = data().deepCopy(fields()[3].schema(), other.settleTimeout);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ChannelOpened instance
     * @param other The existing instance to copy.
     */
    private Builder(io.raidenmap.event.channel.ChannelOpened other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.channelEvent)) {
        this.channelEvent = data().deepCopy(fields()[0].schema(), other.channelEvent);
        fieldSetFlags()[0] = true;
      }
      this.channelEventBuilder = null;
      if (isValidValue(fields()[1], other.participant1)) {
        this.participant1 = data().deepCopy(fields()[1].schema(), other.participant1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.participant2)) {
        this.participant2 = data().deepCopy(fields()[2].schema(), other.participant2);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.settleTimeout)) {
        this.settleTimeout = data().deepCopy(fields()[3].schema(), other.settleTimeout);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'channelEvent' field.
      * @return The value.
      */
    public io.raidenmap.event.channel.ChannelEvent getChannelEvent() {
      return channelEvent;
    }

    /**
      * Sets the value of the 'channelEvent' field.
      * @param value The value of 'channelEvent'.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelOpened.Builder setChannelEvent(io.raidenmap.event.channel.ChannelEvent value) {
      validate(fields()[0], value);
      this.channelEventBuilder = null;
      this.channelEvent = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'channelEvent' field has been set.
      * @return True if the 'channelEvent' field has been set, false otherwise.
      */
    public boolean hasChannelEvent() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'channelEvent' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.raidenmap.event.channel.ChannelEvent.Builder getChannelEventBuilder() {
      if (channelEventBuilder == null) {
        if (hasChannelEvent()) {
          setChannelEventBuilder(io.raidenmap.event.channel.ChannelEvent.newBuilder(channelEvent));
        } else {
          setChannelEventBuilder(io.raidenmap.event.channel.ChannelEvent.newBuilder());
        }
      }
      return channelEventBuilder;
    }

    /**
     * Sets the Builder instance for the 'channelEvent' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public io.raidenmap.event.channel.ChannelOpened.Builder setChannelEventBuilder(io.raidenmap.event.channel.ChannelEvent.Builder value) {
      clearChannelEvent();
      channelEventBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'channelEvent' field has an active Builder instance
     * @return True if the 'channelEvent' field has an active Builder instance
     */
    public boolean hasChannelEventBuilder() {
      return channelEventBuilder != null;
    }

    /**
      * Clears the value of the 'channelEvent' field.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelOpened.Builder clearChannelEvent() {
      channelEvent = null;
      channelEventBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'participant1' field.
      * @return The value.
      */
    public java.lang.CharSequence getParticipant1() {
      return participant1;
    }

    /**
      * Sets the value of the 'participant1' field.
      * @param value The value of 'participant1'.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelOpened.Builder setParticipant1(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.participant1 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'participant1' field has been set.
      * @return True if the 'participant1' field has been set, false otherwise.
      */
    public boolean hasParticipant1() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'participant1' field.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelOpened.Builder clearParticipant1() {
      participant1 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'participant2' field.
      * @return The value.
      */
    public java.lang.CharSequence getParticipant2() {
      return participant2;
    }

    /**
      * Sets the value of the 'participant2' field.
      * @param value The value of 'participant2'.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelOpened.Builder setParticipant2(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.participant2 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'participant2' field has been set.
      * @return True if the 'participant2' field has been set, false otherwise.
      */
    public boolean hasParticipant2() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'participant2' field.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelOpened.Builder clearParticipant2() {
      participant2 = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'settleTimeout' field.
      * @return The value.
      */
    public java.lang.Long getSettleTimeout() {
      return settleTimeout;
    }

    /**
      * Sets the value of the 'settleTimeout' field.
      * @param value The value of 'settleTimeout'.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelOpened.Builder setSettleTimeout(long value) {
      validate(fields()[3], value);
      this.settleTimeout = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'settleTimeout' field has been set.
      * @return True if the 'settleTimeout' field has been set, false otherwise.
      */
    public boolean hasSettleTimeout() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'settleTimeout' field.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelOpened.Builder clearSettleTimeout() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ChannelOpened build() {
      try {
        ChannelOpened record = new ChannelOpened();
        if (channelEventBuilder != null) {
          record.channelEvent = this.channelEventBuilder.build();
        } else {
          record.channelEvent = fieldSetFlags()[0] ? this.channelEvent : (io.raidenmap.event.channel.ChannelEvent) defaultValue(fields()[0]);
        }
        record.participant1 = fieldSetFlags()[1] ? this.participant1 : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.participant2 = fieldSetFlags()[2] ? this.participant2 : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.settleTimeout = fieldSetFlags()[3] ? this.settleTimeout : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ChannelOpened>
    WRITER$ = (org.apache.avro.io.DatumWriter<ChannelOpened>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ChannelOpened>
    READER$ = (org.apache.avro.io.DatumReader<ChannelOpened>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
