/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.raidenmap.event.channel;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ChannelUnlocked extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1229310426553854788L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ChannelUnlocked\",\"namespace\":\"io.raidenmap.event.channel\",\"fields\":[{\"name\":\"channelEvent\",\"type\":{\"type\":\"record\",\"name\":\"ChannelEvent\",\"fields\":[{\"name\":\"metadata\",\"type\":{\"type\":\"record\",\"name\":\"Metadata\",\"namespace\":\"io.raidenmap.event\",\"fields\":[{\"name\":\"blockNumber\",\"type\":\"long\"},{\"name\":\"blockTimestamp\",\"type\":\"long\"},{\"name\":\"eventTimestamp\",\"type\":\"long\"}]}},{\"name\":\"tokenNetworkAddress\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"}]}},{\"name\":\"participant\",\"type\":\"string\"},{\"name\":\"unlockedAmount\",\"type\":\"int\"},{\"name\":\"returnedTokens\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ChannelUnlocked> ENCODER =
      new BinaryMessageEncoder<ChannelUnlocked>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ChannelUnlocked> DECODER =
      new BinaryMessageDecoder<ChannelUnlocked>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ChannelUnlocked> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ChannelUnlocked> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ChannelUnlocked>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ChannelUnlocked to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ChannelUnlocked from a ByteBuffer. */
  public static ChannelUnlocked fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public io.raidenmap.event.channel.ChannelEvent channelEvent;
  @Deprecated public java.lang.CharSequence participant;
  @Deprecated public int unlockedAmount;
  @Deprecated public int returnedTokens;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ChannelUnlocked() {}

  /**
   * All-args constructor.
   * @param channelEvent The new value for channelEvent
   * @param participant The new value for participant
   * @param unlockedAmount The new value for unlockedAmount
   * @param returnedTokens The new value for returnedTokens
   */
  public ChannelUnlocked(io.raidenmap.event.channel.ChannelEvent channelEvent, java.lang.CharSequence participant, java.lang.Integer unlockedAmount, java.lang.Integer returnedTokens) {
    this.channelEvent = channelEvent;
    this.participant = participant;
    this.unlockedAmount = unlockedAmount;
    this.returnedTokens = returnedTokens;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return channelEvent;
    case 1: return participant;
    case 2: return unlockedAmount;
    case 3: return returnedTokens;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: channelEvent = (io.raidenmap.event.channel.ChannelEvent)value$; break;
    case 1: participant = (java.lang.CharSequence)value$; break;
    case 2: unlockedAmount = (java.lang.Integer)value$; break;
    case 3: returnedTokens = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'channelEvent' field.
   * @return The value of the 'channelEvent' field.
   */
  public io.raidenmap.event.channel.ChannelEvent getChannelEvent() {
    return channelEvent;
  }

  /**
   * Sets the value of the 'channelEvent' field.
   * @param value the value to set.
   */
  public void setChannelEvent(io.raidenmap.event.channel.ChannelEvent value) {
    this.channelEvent = value;
  }

  /**
   * Gets the value of the 'participant' field.
   * @return The value of the 'participant' field.
   */
  public java.lang.CharSequence getParticipant() {
    return participant;
  }

  /**
   * Sets the value of the 'participant' field.
   * @param value the value to set.
   */
  public void setParticipant(java.lang.CharSequence value) {
    this.participant = value;
  }

  /**
   * Gets the value of the 'unlockedAmount' field.
   * @return The value of the 'unlockedAmount' field.
   */
  public java.lang.Integer getUnlockedAmount() {
    return unlockedAmount;
  }

  /**
   * Sets the value of the 'unlockedAmount' field.
   * @param value the value to set.
   */
  public void setUnlockedAmount(java.lang.Integer value) {
    this.unlockedAmount = value;
  }

  /**
   * Gets the value of the 'returnedTokens' field.
   * @return The value of the 'returnedTokens' field.
   */
  public java.lang.Integer getReturnedTokens() {
    return returnedTokens;
  }

  /**
   * Sets the value of the 'returnedTokens' field.
   * @param value the value to set.
   */
  public void setReturnedTokens(java.lang.Integer value) {
    this.returnedTokens = value;
  }

  /**
   * Creates a new ChannelUnlocked RecordBuilder.
   * @return A new ChannelUnlocked RecordBuilder
   */
  public static io.raidenmap.event.channel.ChannelUnlocked.Builder newBuilder() {
    return new io.raidenmap.event.channel.ChannelUnlocked.Builder();
  }

  /**
   * Creates a new ChannelUnlocked RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ChannelUnlocked RecordBuilder
   */
  public static io.raidenmap.event.channel.ChannelUnlocked.Builder newBuilder(io.raidenmap.event.channel.ChannelUnlocked.Builder other) {
    return new io.raidenmap.event.channel.ChannelUnlocked.Builder(other);
  }

  /**
   * Creates a new ChannelUnlocked RecordBuilder by copying an existing ChannelUnlocked instance.
   * @param other The existing instance to copy.
   * @return A new ChannelUnlocked RecordBuilder
   */
  public static io.raidenmap.event.channel.ChannelUnlocked.Builder newBuilder(io.raidenmap.event.channel.ChannelUnlocked other) {
    return new io.raidenmap.event.channel.ChannelUnlocked.Builder(other);
  }

  /**
   * RecordBuilder for ChannelUnlocked instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ChannelUnlocked>
    implements org.apache.avro.data.RecordBuilder<ChannelUnlocked> {

    private io.raidenmap.event.channel.ChannelEvent channelEvent;
    private io.raidenmap.event.channel.ChannelEvent.Builder channelEventBuilder;
    private java.lang.CharSequence participant;
    private int unlockedAmount;
    private int returnedTokens;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.raidenmap.event.channel.ChannelUnlocked.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.channelEvent)) {
        this.channelEvent = data().deepCopy(fields()[0].schema(), other.channelEvent);
        fieldSetFlags()[0] = true;
      }
      if (other.hasChannelEventBuilder()) {
        this.channelEventBuilder = io.raidenmap.event.channel.ChannelEvent.newBuilder(other.getChannelEventBuilder());
      }
      if (isValidValue(fields()[1], other.participant)) {
        this.participant = data().deepCopy(fields()[1].schema(), other.participant);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.unlockedAmount)) {
        this.unlockedAmount = data().deepCopy(fields()[2].schema(), other.unlockedAmount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.returnedTokens)) {
        this.returnedTokens = data().deepCopy(fields()[3].schema(), other.returnedTokens);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ChannelUnlocked instance
     * @param other The existing instance to copy.
     */
    private Builder(io.raidenmap.event.channel.ChannelUnlocked other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.channelEvent)) {
        this.channelEvent = data().deepCopy(fields()[0].schema(), other.channelEvent);
        fieldSetFlags()[0] = true;
      }
      this.channelEventBuilder = null;
      if (isValidValue(fields()[1], other.participant)) {
        this.participant = data().deepCopy(fields()[1].schema(), other.participant);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.unlockedAmount)) {
        this.unlockedAmount = data().deepCopy(fields()[2].schema(), other.unlockedAmount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.returnedTokens)) {
        this.returnedTokens = data().deepCopy(fields()[3].schema(), other.returnedTokens);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'channelEvent' field.
      * @return The value.
      */
    public io.raidenmap.event.channel.ChannelEvent getChannelEvent() {
      return channelEvent;
    }

    /**
      * Sets the value of the 'channelEvent' field.
      * @param value The value of 'channelEvent'.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelUnlocked.Builder setChannelEvent(io.raidenmap.event.channel.ChannelEvent value) {
      validate(fields()[0], value);
      this.channelEventBuilder = null;
      this.channelEvent = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'channelEvent' field has been set.
      * @return True if the 'channelEvent' field has been set, false otherwise.
      */
    public boolean hasChannelEvent() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'channelEvent' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public io.raidenmap.event.channel.ChannelEvent.Builder getChannelEventBuilder() {
      if (channelEventBuilder == null) {
        if (hasChannelEvent()) {
          setChannelEventBuilder(io.raidenmap.event.channel.ChannelEvent.newBuilder(channelEvent));
        } else {
          setChannelEventBuilder(io.raidenmap.event.channel.ChannelEvent.newBuilder());
        }
      }
      return channelEventBuilder;
    }

    /**
     * Sets the Builder instance for the 'channelEvent' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public io.raidenmap.event.channel.ChannelUnlocked.Builder setChannelEventBuilder(io.raidenmap.event.channel.ChannelEvent.Builder value) {
      clearChannelEvent();
      channelEventBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'channelEvent' field has an active Builder instance
     * @return True if the 'channelEvent' field has an active Builder instance
     */
    public boolean hasChannelEventBuilder() {
      return channelEventBuilder != null;
    }

    /**
      * Clears the value of the 'channelEvent' field.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelUnlocked.Builder clearChannelEvent() {
      channelEvent = null;
      channelEventBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'participant' field.
      * @return The value.
      */
    public java.lang.CharSequence getParticipant() {
      return participant;
    }

    /**
      * Sets the value of the 'participant' field.
      * @param value The value of 'participant'.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelUnlocked.Builder setParticipant(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.participant = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'participant' field has been set.
      * @return True if the 'participant' field has been set, false otherwise.
      */
    public boolean hasParticipant() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'participant' field.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelUnlocked.Builder clearParticipant() {
      participant = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'unlockedAmount' field.
      * @return The value.
      */
    public java.lang.Integer getUnlockedAmount() {
      return unlockedAmount;
    }

    /**
      * Sets the value of the 'unlockedAmount' field.
      * @param value The value of 'unlockedAmount'.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelUnlocked.Builder setUnlockedAmount(int value) {
      validate(fields()[2], value);
      this.unlockedAmount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'unlockedAmount' field has been set.
      * @return True if the 'unlockedAmount' field has been set, false otherwise.
      */
    public boolean hasUnlockedAmount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'unlockedAmount' field.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelUnlocked.Builder clearUnlockedAmount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'returnedTokens' field.
      * @return The value.
      */
    public java.lang.Integer getReturnedTokens() {
      return returnedTokens;
    }

    /**
      * Sets the value of the 'returnedTokens' field.
      * @param value The value of 'returnedTokens'.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelUnlocked.Builder setReturnedTokens(int value) {
      validate(fields()[3], value);
      this.returnedTokens = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'returnedTokens' field has been set.
      * @return True if the 'returnedTokens' field has been set, false otherwise.
      */
    public boolean hasReturnedTokens() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'returnedTokens' field.
      * @return This builder.
      */
    public io.raidenmap.event.channel.ChannelUnlocked.Builder clearReturnedTokens() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ChannelUnlocked build() {
      try {
        ChannelUnlocked record = new ChannelUnlocked();
        if (channelEventBuilder != null) {
          record.channelEvent = this.channelEventBuilder.build();
        } else {
          record.channelEvent = fieldSetFlags()[0] ? this.channelEvent : (io.raidenmap.event.channel.ChannelEvent) defaultValue(fields()[0]);
        }
        record.participant = fieldSetFlags()[1] ? this.participant : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.unlockedAmount = fieldSetFlags()[2] ? this.unlockedAmount : (java.lang.Integer) defaultValue(fields()[2]);
        record.returnedTokens = fieldSetFlags()[3] ? this.returnedTokens : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ChannelUnlocked>
    WRITER$ = (org.apache.avro.io.DatumWriter<ChannelUnlocked>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ChannelUnlocked>
    READER$ = (org.apache.avro.io.DatumReader<ChannelUnlocked>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
