/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.raidenmap;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Endpoint extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1465902282320937486L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Endpoint\",\"namespace\":\"io.raidenmap\",\"fields\":[{\"name\":\"ethAddress\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ipAddress\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"state\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"latitude\",\"type\":\"float\"},{\"name\":\"longitude\",\"type\":\"float\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Endpoint> ENCODER =
      new BinaryMessageEncoder<Endpoint>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Endpoint> DECODER =
      new BinaryMessageDecoder<Endpoint>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Endpoint> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Endpoint> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Endpoint>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Endpoint to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Endpoint from a ByteBuffer. */
  public static Endpoint fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String ethAddress;
  @Deprecated public java.lang.String ipAddress;
  @Deprecated public java.lang.String state;
  @Deprecated public float latitude;
  @Deprecated public float longitude;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Endpoint() {}

  /**
   * All-args constructor.
   * @param ethAddress The new value for ethAddress
   * @param ipAddress The new value for ipAddress
   * @param state The new value for state
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   */
  public Endpoint(java.lang.String ethAddress, java.lang.String ipAddress, java.lang.String state, java.lang.Float latitude, java.lang.Float longitude) {
    this.ethAddress = ethAddress;
    this.ipAddress = ipAddress;
    this.state = state;
    this.latitude = latitude;
    this.longitude = longitude;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ethAddress;
    case 1: return ipAddress;
    case 2: return state;
    case 3: return latitude;
    case 4: return longitude;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ethAddress = (java.lang.String)value$; break;
    case 1: ipAddress = (java.lang.String)value$; break;
    case 2: state = (java.lang.String)value$; break;
    case 3: latitude = (java.lang.Float)value$; break;
    case 4: longitude = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ethAddress' field.
   * @return The value of the 'ethAddress' field.
   */
  public java.lang.String getEthAddress() {
    return ethAddress;
  }

  /**
   * Sets the value of the 'ethAddress' field.
   * @param value the value to set.
   */
  public void setEthAddress(java.lang.String value) {
    this.ethAddress = value;
  }

  /**
   * Gets the value of the 'ipAddress' field.
   * @return The value of the 'ipAddress' field.
   */
  public java.lang.String getIpAddress() {
    return ipAddress;
  }

  /**
   * Sets the value of the 'ipAddress' field.
   * @param value the value to set.
   */
  public void setIpAddress(java.lang.String value) {
    this.ipAddress = value;
  }

  /**
   * Gets the value of the 'state' field.
   * @return The value of the 'state' field.
   */
  public java.lang.String getState() {
    return state;
  }

  /**
   * Sets the value of the 'state' field.
   * @param value the value to set.
   */
  public void setState(java.lang.String value) {
    this.state = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public java.lang.Float getLatitude() {
    return latitude;
  }

  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(java.lang.Float value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public java.lang.Float getLongitude() {
    return longitude;
  }

  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(java.lang.Float value) {
    this.longitude = value;
  }

  /**
   * Creates a new Endpoint RecordBuilder.
   * @return A new Endpoint RecordBuilder
   */
  public static io.raidenmap.Endpoint.Builder newBuilder() {
    return new io.raidenmap.Endpoint.Builder();
  }

  /**
   * Creates a new Endpoint RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Endpoint RecordBuilder
   */
  public static io.raidenmap.Endpoint.Builder newBuilder(io.raidenmap.Endpoint.Builder other) {
    return new io.raidenmap.Endpoint.Builder(other);
  }

  /**
   * Creates a new Endpoint RecordBuilder by copying an existing Endpoint instance.
   * @param other The existing instance to copy.
   * @return A new Endpoint RecordBuilder
   */
  public static io.raidenmap.Endpoint.Builder newBuilder(io.raidenmap.Endpoint other) {
    return new io.raidenmap.Endpoint.Builder(other);
  }

  /**
   * RecordBuilder for Endpoint instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Endpoint>
    implements org.apache.avro.data.RecordBuilder<Endpoint> {

    private java.lang.String ethAddress;
    private java.lang.String ipAddress;
    private java.lang.String state;
    private float latitude;
    private float longitude;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.raidenmap.Endpoint.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ethAddress)) {
        this.ethAddress = data().deepCopy(fields()[0].schema(), other.ethAddress);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[1].schema(), other.ipAddress);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.latitude)) {
        this.latitude = data().deepCopy(fields()[3].schema(), other.latitude);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.longitude)) {
        this.longitude = data().deepCopy(fields()[4].schema(), other.longitude);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Endpoint instance
     * @param other The existing instance to copy.
     */
    private Builder(io.raidenmap.Endpoint other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.ethAddress)) {
        this.ethAddress = data().deepCopy(fields()[0].schema(), other.ethAddress);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[1].schema(), other.ipAddress);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.state)) {
        this.state = data().deepCopy(fields()[2].schema(), other.state);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.latitude)) {
        this.latitude = data().deepCopy(fields()[3].schema(), other.latitude);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.longitude)) {
        this.longitude = data().deepCopy(fields()[4].schema(), other.longitude);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'ethAddress' field.
      * @return The value.
      */
    public java.lang.String getEthAddress() {
      return ethAddress;
    }

    /**
      * Sets the value of the 'ethAddress' field.
      * @param value The value of 'ethAddress'.
      * @return This builder.
      */
    public io.raidenmap.Endpoint.Builder setEthAddress(java.lang.String value) {
      validate(fields()[0], value);
      this.ethAddress = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ethAddress' field has been set.
      * @return True if the 'ethAddress' field has been set, false otherwise.
      */
    public boolean hasEthAddress() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ethAddress' field.
      * @return This builder.
      */
    public io.raidenmap.Endpoint.Builder clearEthAddress() {
      ethAddress = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ipAddress' field.
      * @return The value.
      */
    public java.lang.String getIpAddress() {
      return ipAddress;
    }

    /**
      * Sets the value of the 'ipAddress' field.
      * @param value The value of 'ipAddress'.
      * @return This builder.
      */
    public io.raidenmap.Endpoint.Builder setIpAddress(java.lang.String value) {
      validate(fields()[1], value);
      this.ipAddress = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ipAddress' field has been set.
      * @return True if the 'ipAddress' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ipAddress' field.
      * @return This builder.
      */
    public io.raidenmap.Endpoint.Builder clearIpAddress() {
      ipAddress = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'state' field.
      * @return The value.
      */
    public java.lang.String getState() {
      return state;
    }

    /**
      * Sets the value of the 'state' field.
      * @param value The value of 'state'.
      * @return This builder.
      */
    public io.raidenmap.Endpoint.Builder setState(java.lang.String value) {
      validate(fields()[2], value);
      this.state = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'state' field has been set.
      * @return True if the 'state' field has been set, false otherwise.
      */
    public boolean hasState() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'state' field.
      * @return This builder.
      */
    public io.raidenmap.Endpoint.Builder clearState() {
      state = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public java.lang.Float getLatitude() {
      return latitude;
    }

    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public io.raidenmap.Endpoint.Builder setLatitude(float value) {
      validate(fields()[3], value);
      this.latitude = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public io.raidenmap.Endpoint.Builder clearLatitude() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public java.lang.Float getLongitude() {
      return longitude;
    }

    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public io.raidenmap.Endpoint.Builder setLongitude(float value) {
      validate(fields()[4], value);
      this.longitude = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public io.raidenmap.Endpoint.Builder clearLongitude() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Endpoint build() {
      try {
        Endpoint record = new Endpoint();
        record.ethAddress = fieldSetFlags()[0] ? this.ethAddress : (java.lang.String) defaultValue(fields()[0]);
        record.ipAddress = fieldSetFlags()[1] ? this.ipAddress : (java.lang.String) defaultValue(fields()[1]);
        record.state = fieldSetFlags()[2] ? this.state : (java.lang.String) defaultValue(fields()[2]);
        record.latitude = fieldSetFlags()[3] ? this.latitude : (java.lang.Float) defaultValue(fields()[3]);
        record.longitude = fieldSetFlags()[4] ? this.longitude : (java.lang.Float) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Endpoint>
    WRITER$ = (org.apache.avro.io.DatumWriter<Endpoint>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Endpoint>
    READER$ = (org.apache.avro.io.DatumReader<Endpoint>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
